name: Android Lint
run-name: Running Lint

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
     - uses: action/checkout@v3
     - name: Setup JDK 17
       uses: action/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle

     - name: Run Lint
       run: ./gradlew lint
       continue-on-error: false
